

libname frmt "/sasdata/users/&sysuserid./tmsisshare/prod/01_AREMAC/Task_12/DQ_SAS/002_lookups";

proc format library = frmt.states;

    value $ st_usps
        '01' = "AL"
        '02' = "AK"
        '04' = "AZ"
        '05' = "AR"
        '06' = "CA"
        '08' = "CO"
        '09' = "CT"
        '10' = "DE"
        '11' = "DC"
        '12' = "FL"
        '13' = "GA"
        '15' = "HI"
        '16' = "ID"
        '17' = "IL"
        '18' = "IN"
        '19' = "IA"
        '20' = "KS"
        '21' = "KY"
        '22' = "LA"
        '23' = "ME"
        '24' = "MD"
        '25' = "MA"
        '26' = "MI"
        '27' = "MN"
        '28' = "MS"
        '29' = "MO"
        '30' = "MT"
        '31' = "NE"
        '32' = "NV"
        '33' = "NH"
        '34' = "NJ"
        '35' = "NM"
        '36' = "NY"
        '37' = "NC"
        '38' = "ND"
        '39' = "OH"
        '40' = "OK"
        '41' = "OR"
        '42' = "PA"
        '44' = "RI"
        '45' = "SC"
        '46' = "SD"
        '47' = "TN"
        '48' = "TX"
        '49' = "UT"
        '50' = "VT"
        '51' = "VA"
        '53' = "WA"
        '54' = "WV"
        '55' = "WI"
        '56' = "WY"
        '72' = "PR"
        '78' = "VI"
		'93' = "WY"
		'94' = "MT"
        '96' = "IA"
        '97' = "PA"
        Other = "XX"
        ;

    value $ st_name
        '01' = "Alabama"
        '02' = "Alaska"
        '04' = "Arizona"
        '05' = "Arkansas"
        '06' = "California"
        '08' = "Colorado"
        '09' = "Connecticut"
        '10' = "Delaware"
        '11' = "District of Columbia"
        '12' = "Florida"
        '13' = "Georgia"
        '15' = "Hawaii"
        '16' = "Idaho"
        '17' = "Illinois"
        '18' = "Indiana"
        '19' = "Iowa"
        '20' = "Kansas"
        '21' = "Kentucky"
        '22' = "Louisiana"
        '23' = "Maine"
        '24' = "Maryland"
        '25' = "Massachusetts"
        '26' = "Michigan"
        '27' = "Minnesota"
        '28' = "Mississippi"
        '29' = "Missouri"
        '30' = "Montana"
        '31' = "Nebraska"
        '32' = "Nevada"
        '33' = "New Hampshire"
        '34' = "New Jersey"
        '35' = "New Mexico"
        '36' = "New York"
        '37' = "North Carolina"
        '38' = "North Dakota"
        '39' = "Ohio"
        '40' = "Oklahoma"
        '41' = "Oregon"
        '42' = "Pennsylvania"
        '44' = "Rhode Island"
        '45' = "South Carolina"
        '46' = "South Dakota"
        '47' = "Tennessee"
        '48' = "Texas"
        '49' = "Utah"
        '50' = "Vermont"
        '51' = "Virginia"
        '53' = "Washington"
        '54' = "West Virginia"
        '55' = "Wisconsin"
        '56' = "Wyoming"
        '72' = "Puerto Rico"
        '78' = "Virgin Islands"
		'93' = "Wyoming"
		'94' = "Montana"
        '96' = "Iowa"
        '97' = "Pennsylvania"
        Other = "Not Valid State"
        ;

    value $ st_fips
        'AL' = '01'
        'AK' = '02'
        'AZ' = '04'
        'AR' = '05'
        'CA' = '06'
        'CO' = '08'
        'CT' = '09'
        'DE' = '10'
        'DC' = '11'
        'FL' = '12'
        'GA' = '13'
        'HI' = '15'
        'ID' = '16'
        'IL' = '17'
        'IN' = '18'
        'IA' = '19,96'
        'KS' = '20'
        'KY' = '21'
        'LA' = '22'
        'ME' = '23'
        'MD' = '24'
        'MA' = '25'
        'MI' = '26'
        'MN' = '27'
        'MS' = '28'
        'MO' = '29'
        'MT' = '30,94'
        'NE' = '31'
        'NV' = '32'
        'NH' = '33'
        'NJ' = '34'
        'NM' = '35'
        'NY' = '36'
        'NC' = '37'
        'ND' = '38'
        'OH' = '39'
        'OK' = '40'
        'OR' = '41'
        'PA' = '42,97'
        'PR' = '72'
        'RI' = '44'
        'SC' = '45'
        'SD' = '46'
        'TN' = '47'
        'TX' = '48'
        'UT' = '49'
        'VT' = '50'
        'VA' = '51'
        'VI' = '78'	
        'WA' = '53'
        'WV' = '54'
        'WI' = '55'
        'WY' = '56,93'
        ;


    value $ st2_name
        'AL' = "Alabama"
        'AK' = "Alaska"
        'AZ' = "Arizona"
        'AR' = "Arkansas"
        'CA' = "California"
        'CO' = "Colorado"
        'CT' = "Connecticut"
        'DE' = "Delaware"
        'DC' = "District of Columbia"
        'FL' = "Florida"
        'GA' = "Georgia"
        'HI' = "Hawaii"
        'ID' = "Idaho"
        'IL' = "Illinois"
        'IN' = "Indiana"
        'IA' = "Iowa"
        'KS' = "Kansas"
        'KY' = "Kentucky"
        'LA' = "Louisiana"
        'ME' = "Maine"
        'MD' = "Maryland"
        'MA' = "Massachusetts"
        'MI' = "Michigan"
        'MN' = "Minnesota"
        'MS' = "Mississippi"
        'MO' = "Missouri"
        'MT' = "Montana"
        'NE' = "Nebraska"
        'NV' = "Nevada"
        'NH' = "New Hampshire"
        'NJ' = "New Jersey"
        'NM' = "New Mexico"
        'NY' = "New York"
        'NC' = "North Carolina"
        'ND' = "North Dakota"
        'OH' = "Ohio"
        'OK' = "Oklahoma"
        'OR' = "Oregon"
        'PA' = "Pennsylvania"
        'PR' = "Puerto Rico"
        'RI' = "Rhode Island"
        'SC' = "South Carolina"
        'SD' = "South Dakota"
        'TN' = "Tennessee"
        'TX' = "Texas"
        'UT' = "Utah"
        'VI' = "Virgin Islands"
        'VT' = "Vermont"
        'VA' = "Virginia"
        'WA' = "Washington"
        'WV' = "West Virginia"
        'WI' = "Wisconsin"
        'WY' = "Wyoming"
        Other = "Not Valid State"
        ;

		* V1.7, for FMG table;
		value $stabr
        'Alabama' = 'AL'
        'Alaska' = 'AK'
        'Amer. Samoa' = 'AS'
        'Arizona' = 'AZ'
        'Arkansas' = 'AR'
        'California' = 'CA'
        'Colorado' = 'CO'
        'Connecticut' = 'CT'
        'Delaware' = 'DE'
        'Dist. Of Col.' = 'DC'
        'Florida' = 'FL'
        'Georgia' = 'GA'
        'Hawaii' = 'HI'
        'Idaho' = 'ID'
        'Illinois' = 'IL'
        'Indiana' = 'IN'
        'Iowa' = 'IA'
        'Kansas' = 'KS'
        'Kentucky' = 'KY'
        'Louisiana' = 'LA'
        'Maine' = 'ME'
        'Maryland' = 'MD'
        'Massachusetts' = 'MA'
        'Michigan' = 'MI'
        'Minnesota' = 'MN'
        'Mississippi' = 'MS'
        'Missouri' = 'MO'
        'Montana' = 'MT'
        'Nebraska' = 'NE'
        'Nevada' = 'NV'
        'New Hampshire' = 'NH'
        'New Jersey' = 'NJ'
        'New Mexico' = 'NM'
        'New York' = 'NY'
        'North Carolina' = 'NC'
        'North Dakota' = 'ND'
        'Ohio' = 'OH'
        'Oklahoma' = 'OK'
        'Oregon' = 'OR'
        'Pennsylvania' = 'PA'
        'Puerto Rico' = 'PR'
        'Rhode Island' = 'RI'
        'South Carolina' = 'SC'
        'South Dakota' = 'SD'
        'Tennessee' = 'TN'
        'Texas' = 'TX'
        'Utah' = 'UT'
        'Vermont' = 'VT'
        'Virginia' = 'VA'
        'Washington' = 'WA'
        'West Virginia' = 'WV'
        'Wisconsin' = 'WI'
        'Wyoming' = 'WY'
        'N. Mariana Islands' = 'MP'
        'Virgin Islands' = 'VI'
        'Guam' = 'GU'
        ;
run;
