databricks --profile prod jobs reset --job-id 3499   --json-file ./jobs/PROD/alabama.json
databricks --profile prod jobs reset --job-id 3680   --json-file ./jobs/PROD/alaska.json
databricks --profile prod jobs reset --job-id 934    --json-file ./jobs/PROD/arizona.json
databricks --profile prod jobs reset --job-id 3402   --json-file ./jobs/PROD/arkansas.json

databricks --profile prod jobs reset --job-id 314    --json-file ./jobs/PROD/california.json
databricks --profile prod jobs reset --job-id 12718  --json-file ./jobs/PROD/california_900.json
databricks --profile prod jobs reset --job-id 12757  --json-file ./jobs/PROD/california_800.json
databricks --profile prod jobs reset --job-id 12781  --json-file ./jobs/PROD/california_700.json
databricks --profile prod jobs reset --job-id 12818  --json-file ./jobs/PROD/california_600.json
databricks --profile prod jobs reset --job-id 12877  --json-file ./jobs/PROD/california_500.json
databricks --profile prod jobs reset --job-id 12896  --json-file ./jobs/PROD/california_200.json
databricks --profile prod jobs reset --job-id 12964  --json-file ./jobs/PROD/california_100.json
databricks --profile prod jobs reset --job-id 13006  --json-file ./jobs/PROD/california_reports.json

databricks --profile prod jobs reset --job-id 3727   --json-file ./jobs/PROD/colorado.json
databricks --profile prod jobs reset --job-id 3824   --json-file ./jobs/PROD/connecticut.json
databricks --profile prod jobs reset --job-id 1071   --json-file ./jobs/PROD/district_of_columbia.json
databricks --profile prod jobs reset --job-id 3854   --json-file ./jobs/PROD/delaware.json
databricks --profile prod jobs reset --job-id 740    --json-file ./jobs/PROD/florida.json
databricks --profile prod jobs reset --job-id 3915   --json-file ./jobs/PROD/georgia.json
databricks --profile prod jobs reset --job-id 999    --json-file ./jobs/PROD/hawaii.json
databricks --profile prod jobs reset --job-id 3949   --json-file ./jobs/PROD/idaho.json
databricks --profile prod jobs reset --job-id 3951   --json-file ./jobs/PROD/illinois.json
databricks --profile prod jobs reset --job-id 787    --json-file ./jobs/PROD/indiana.json
databricks --profile prod jobs reset --job-id 3935   --json-file ./jobs/PROD/iowa.json
databricks --profile prod jobs reset --job-id 3980   --json-file ./jobs/PROD/kansas.json
databricks --profile prod jobs reset --job-id 4003   --json-file ./jobs/PROD/kentucky.json
databricks --profile prod jobs reset --job-id 4008   --json-file ./jobs/PROD/louisiana.json
databricks --profile prod jobs reset --job-id 4180   --json-file ./jobs/PROD/maine.json
databricks --profile prod jobs reset --job-id 4016   --json-file ./jobs/PROD/maryland.json
databricks --profile prod jobs reset --job-id 4100   --json-file ./jobs/PROD/massachusetts.json
databricks --profile prod jobs reset --job-id 4258   --json-file ./jobs/PROD/michigan.json
databricks --profile prod jobs reset --job-id 4261   --json-file ./jobs/PROD/minnesota.json
databricks --profile prod jobs reset --job-id 4314   --json-file ./jobs/PROD/mississippi.json
databricks --profile prod jobs reset --job-id 4264   --json-file ./jobs/PROD/missouri.json
databricks --profile prod jobs reset --job-id 4322   --json-file ./jobs/PROD/montana.json
databricks --profile prod jobs reset --job-id 887    --json-file ./jobs/PROD/nebraska.json
databricks --profile prod jobs reset --job-id 564    --json-file ./jobs/PROD/nevada.json
databricks --profile prod jobs reset --job-id 4485   --json-file ./jobs/PROD/new_hampshire.json
databricks --profile prod jobs reset --job-id 4576   --json-file ./jobs/PROD/new_jersey.json
databricks --profile prod jobs reset --job-id 4590   --json-file ./jobs/PROD/new_mexico.json
databricks --profile prod jobs reset --job-id 464    --json-file ./jobs/PROD/new_york.json
databricks --profile prod jobs reset --job-id 4346   --json-file ./jobs/PROD/north_carolina.json
databricks --profile prod jobs reset --job-id 4427   --json-file ./jobs/PROD/north_dakota.json
databricks --profile prod jobs reset --job-id 868    --json-file ./jobs/PROD/ohio.json
databricks --profile prod jobs reset --job-id 4606   --json-file ./jobs/PROD/oklahoma.json
databricks --profile prod jobs reset --job-id 31041  --json-file ./jobs/PROD/oregon.json
databricks --profile prod jobs reset --job-id 4740   --json-file ./jobs/PROD/pennsylvania_medicaid.json
databricks --profile prod jobs reset --job-id 4673   --json-file ./jobs/PROD/pennsylvania_chip.json
databricks --profile prod jobs reset --job-id 4806   --json-file ./jobs/PROD/puerto_rico.json
databricks --profile prod jobs reset --job-id 4849   --json-file ./jobs/PROD/rhode_island.json
databricks --profile prod jobs reset --job-id 4933   --json-file ./jobs/PROD/south_carolina.json
databricks --profile prod jobs reset --job-id 4971   --json-file ./jobs/PROD/south_dakota.json
databricks --profile prod jobs reset --job-id 4974   --json-file ./jobs/PROD/tennessee.json
databricks --profile prod jobs reset --job-id 1188   --json-file ./jobs/PROD/texas.json
databricks --profile prod jobs reset --job-id 5034   --json-file ./jobs/PROD/utah.json
databricks --profile prod jobs reset --job-id 5148   --json-file ./jobs/PROD/vermont.json
databricks --profile prod jobs reset --job-id 1126   --json-file ./jobs/PROD/us_virgin_islands.json
databricks --profile prod jobs reset --job-id 3586   --json-file ./jobs/PROD/virginia.json
databricks --profile prod jobs reset --job-id 987    --json-file ./jobs/PROD/washington.json
databricks --profile prod jobs reset --job-id 5055   --json-file ./jobs/PROD/west_virginia.json
databricks --profile prod jobs reset --job-id 3549   --json-file ./jobs/PROD/wisconsin.json
databricks --profile prod jobs reset --job-id 5086   --json-file ./jobs/PROD/wyoming_medicaid.json
