databricks --profile val jobs reset --job-id 77011 --json-file .\jobs\VAL\alabama.json
databricks --profile val jobs reset --job-id 77101 --json-file .\jobs\VAL\alaska.json
databricks --profile val jobs reset --job-id 77140 --json-file .\jobs\VAL\arizona.json
databricks --profile val jobs reset --job-id 77185 --json-file .\jobs\VAL\arkansas.json

databricks --profile val jobs reset --job-id 77251 --json-file .\jobs\VAL\california.json
databricks --profile val jobs reset --job-id 598923  --json-file .\jobs\PROD\california_prep.json
databricks --profile val jobs reset --job-id 598736  --json-file .\jobs\PROD\california_900.json
databricks --profile val jobs reset --job-id 598725  --json-file .\jobs\PROD\california_800.json
databricks --profile val jobs reset --job-id 598691  --json-file .\jobs\PROD\california_700.json
databricks --profile val jobs reset --job-id 598637  --json-file .\jobs\PROD\california_600.json
databricks --profile val jobs reset --job-id 598619  --json-file .\jobs\PROD\california_500.json
databricks --profile val jobs reset --job-id 598578  --json-file .\jobs\PROD\california_200.json
databricks --profile val jobs reset --job-id 598532  --json-file .\jobs\PROD\california_100.json
databricks --profile val jobs reset --job-id 598747  --json-file .\jobs\PROD\california_reports.json

databricks --profile val jobs reset --job-id 77643 --json-file .\jobs\VAL\colorado.json
databricks --profile val jobs reset --job-id 77712 --json-file .\jobs\VAL\connecticut.json
databricks --profile val jobs reset --job-id 77842 --json-file .\jobs\VAL\district_of_columbia.json
databricks --profile val jobs reset --job-id 77761 --json-file .\jobs\VAL\delaware.json
databricks --profile val jobs reset --job-id 77844 --json-file .\jobs\VAL\florida.json
databricks --profile val jobs reset --job-id 77886 --json-file .\jobs\VAL\georgia.json
databricks --profile val jobs reset --job-id 77893 --json-file .\jobs\VAL\hawaii.json
databricks --profile val jobs reset --job-id 77979 --json-file .\jobs\VAL\idaho.json
databricks --profile val jobs reset --job-id 78047 --json-file .\jobs\VAL\illinois.json
databricks --profile val jobs reset --job-id 78114 --json-file .\jobs\VAL\indiana.json
databricks --profile val jobs reset --job-id 78209 --json-file .\jobs\VAL\iowa.json
databricks --profile val jobs reset --job-id 78280 --json-file .\jobs\VAL\kansas.json
databricks --profile val jobs reset --job-id 78331 --json-file .\jobs\VAL\kentucky.json
databricks --profile val jobs reset --job-id 78377 --json-file .\jobs\VAL\louisiana.json
databricks --profile val jobs reset --job-id 78441 --json-file .\jobs\VAL\maine.json
databricks --profile val jobs reset --job-id 78509 --json-file .\jobs\VAL\maryland.json
databricks --profile val jobs reset --job-id 78565 --json-file .\jobs\VAL\massachusetts.json
databricks --profile val jobs reset --job-id 78614 --json-file .\jobs\VAL\michigan.json
databricks --profile val jobs reset --job-id 78684 --json-file .\jobs\VAL\minnesota.json
databricks --profile val jobs reset --job-id 78777 --json-file .\jobs\VAL\mississippi.json
databricks --profile val jobs reset --job-id 78788 --json-file .\jobs\VAL\missouri.json
databricks --profile val jobs reset --job-id 78887 --json-file .\jobs\VAL\montana.json
databricks --profile val jobs reset --job-id 78977 --json-file .\jobs\VAL\nebraska.json
databricks --profile val jobs reset --job-id 79063 --json-file .\jobs\VAL\nevada.json
databricks --profile val jobs reset --job-id 79143 --json-file .\jobs\VAL\new_hampshire.json
databricks --profile val jobs reset --job-id 79221 --json-file .\jobs\VAL\new_jersey.json
databricks --profile val jobs reset --job-id 79312 --json-file .\jobs\VAL\new_mexico.json
databricks --profile val jobs reset --job-id 79374 --json-file .\jobs\VAL\new_york.json
databricks --profile val jobs reset --job-id 79399 --json-file .\jobs\VAL\north_carolina.json
databricks --profile val jobs reset --job-id 79424 --json-file .\jobs\VAL\north_dakota.json
databricks --profile val jobs reset --job-id 79472 --json-file .\jobs\VAL\ohio.json
databricks --profile val jobs reset --job-id 79550 --json-file .\jobs\VAL\oklahoma.json
databricks --profile val jobs reset --job-id 79595 --json-file .\jobs\VAL\oregon.json
databricks --profile val jobs reset --job-id 79672 --json-file .\jobs\VAL\pennsylvania_chip.json
databricks --profile val jobs reset --job-id 79717 --json-file .\jobs\VAL\pennsylvania_medicaid.json
databricks --profile val jobs reset --job-id 79773 --json-file .\jobs\VAL\puerto_rico.json
databricks --profile val jobs reset --job-id 79811 --json-file .\jobs\VAL\rhode_island.json
databricks --profile val jobs reset --job-id 79823 --json-file .\jobs\VAL\south_carolina.json
databricks --profile val jobs reset --job-id 79831 --json-file .\jobs\VAL\south_dakota.json
databricks --profile val jobs reset --job-id 79913 --json-file .\jobs\VAL\tennessee.json
databricks --profile val jobs reset --job-id 80006 --json-file .\jobs\VAL\texas.json
databricks --profile val jobs reset --job-id 80078 --json-file .\jobs\VAL\utah.json
databricks --profile val jobs reset --job-id 80140 --json-file .\jobs\VAL\vermont.json
databricks --profile val jobs reset --job-id 80053 --json-file .\jobs\VAL\us_virgin_islands.json
databricks --profile val jobs reset --job-id 80201 --json-file .\jobs\VAL\virginia.json
databricks --profile val jobs reset --job-id 80263 --json-file .\jobs\VAL\washington.json
databricks --profile val jobs reset --job-id 80264 --json-file .\jobs\VAL\west_virginia.json
databricks --profile val jobs reset --job-id 80341 --json-file .\jobs\VAL\wisconsin.json
databricks --profile val jobs reset --job-id 80397 --json-file .\jobs\VAL\wyoming_medicaid.json
